MAIN_RAILWAY_STATIONS: list[str] = [
    'Wrocław Główny',
    'Kraków Główny',
    'Warszawa Centralna',
    'Szczecin Główny',
    'Rzeszów Główny',
    'Gdańsk Wrzeszcz',
    'Łódź Widzew',
    'Kołobrzeg',
    'Poznań Główny',
    'Katowice',
    'Białystok',
    'Częstochowa Stradom',
    'Lublin Główny',
    'Bydgoszcz Główna',
    'Olsztyn Główny',
    'Gdynia Główna',
    ]

MODELING_READY_COLNAMES_BLACKLIST: list[str] = [
    'lat',
    'lon',
    'key',
    'prev_stations',
    'next_stations',
    'encoded_polylines',
    'decoded_polylines',
    'nazwa_wojewodztwo',
    'id_wojewodztwo',
    'nazwa_powiat',
    'id_powiat',
    'nazwa_gmina',
    'id_gmina',
    ]